spring:
  application:
    # 应用名称
    # 用于在日志中显示应用名称
    # 也可以在配置文件中配置
    name: demo
  datasource:
    url: "jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: root
    password: qwe123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
